export const infos = [
  {
    id: 0,
    link: ' assets/logos/twitch.png',
    primary: '#9146FF',
    secondary: '#FFFFFF',
    others: ['#000000'],
    category: 'websites',
    name: 'Twitch',
  },
  {
    id: 1,
    link: ' assets/logos/instagram.png',
    primary: '',
    secondary: '',
    others: ['#8503FC', '#FC00D9', '#FF073F', '#FFC500', '#FFFFFF'],
    category: 'websites',
    name: 'Instagram',
  },
  {
    id: 2,
    link: ' assets/logos/youtube.png',
    primary: '#FF0000',
    secondary: '#FFFFFF',
    others: [],
    category: 'websites',
    name: 'YouTube',
  },
  {
    id: 3,
    link: ' assets/logos/google.png',
    primary: '',
    secondary: '',
    others: ['#EA4335', '#FBBC05', '#34A853', '#4285F4'],
    category: 'websites',
    name: 'Google',
  },
  {
    id: 4,
    link: ' assets/logos/facebook.png',
    primary: '#1877F2',
    secondary: '#FFFFFF',
    others: [],
    category: 'websites',
    name: 'Facebook',
  },
  {
    id: 5,
    link: ' assets/logos/wikipedia.png',
    primary: '#FAFAFA',
    secondary: '#848484',
    others: ['#000000'],
    category: 'websites',
    name: 'Wikipedia',
  },
  {
    id: 6,
    link: ' assets/logos/linkedin.png',
    primary: '#0075B4',
    secondary: '#FFFFFF',
    others: [],
    category: 'websites',
    name: 'LinkedIn',
  },
  {
    id: 7,
    link: ' assets/logos/snapchat.png',
    primary: '#FFFC00',
    secondary: '#FFFFFF',
    others: ['#000000'],
    category: 'websites',
    name: 'SnapChat',
  },
  {
    id: 8,
    link: ' assets/logos/tiktok.png',
    primary: '#000000',
    secondary: '#FFFFFF',
    others: ['#F20544', '#05F2DB'],
    category: 'websites',
    name: 'TikTok',
  },
  {
    id: 9,
    link: ' assets/logos/whatsapp.png',
    primary: '#35DB53',
    secondary: '#FAFAFA',
    others: [],
    category: 'websites',
    name: 'WhatsApp',
  },
  {
    id: 9,
    link: ' assets/logos/whatsapp.png',
    primary: '#35DB53',
    secondary: '#FAFAFA',
    others: [],
    category: 'websites',
    name: 'WhatsApp',
  },
  {
    id: 10,
    link: ' assets/logos/duolingo.png',
    primary: '#58CC02',
    secondary: '#89E219',
    others: ['#FFC200', '#F48000', '#4B4B4B'],
    category: 'websites',
    name: 'Duolingo',
  },
  {
    id: 11,
    link: ' assets/logos/shopee.png',
    primary: '#FF6533',
    secondary: '#FFFFFF',
    others: ['#F6402D'],
    category: 'websites',
    name: 'Shopee',
  },
  {
    id: 12,
    link: ' assets/logos/spotify.png',
    primary: '#1ED760',
    secondary: '#000000',
    others: [],
    category: 'websites',
    name: 'Spotify',
  },
  {
    id: 13,
    link: ' assets/logos/tinder.jpeg',
    primary: '#FC267E',
    secondary: '#FFFFFF',
    others: ['#FF7755'],
    category: 'websites',
    name: 'Tinder',
  },
  {
    id: 14,
    link: ' assets/logos/telegram.png',
    primary: '#239CD7',
    secondary: '#FFFFFF',
    others: [],
    category: 'websites',
    name: 'Telegram',
  },
  {
    id: 15,
    link: ' assets/logos/chatgpt.png',
    primary: '#02A67E',
    secondary: '#000000',
    others: [],
    category: 'websites',
    name: 'ChatGPT',
  },
  {
    id: 16,
    link: ' assets/logos/powerpoint.png',
    primary: '#C23B23',
    secondary: '#F9F7F7',
    others: ['#D15035', '#FD8D6F', '#EB6A4C'],
    category: 'websites',
    name: 'PowerPoint',
  },
  {
    id: 17,
    link: ' assets/logos/edge.png',
    primary: '',
    secondary: '',
    others: ['#017AD5', '#0F5196', '#32C1E6', '#36C752'],
    category: 'websites',
    name: 'Microsoft Edge',
  },
  {
    id: 18,
    link: ' assets/logos/lazada.png',
    primary: '#140D97',
    secondary: '',
    others: ['#CC3C7B', '#EF7622', '#FFFFFF'],
    category: 'websites',
    name: 'Lazada',
  },
  {
    id: 19,
    link: ' assets/logos/discord.png',
    primary: '#5C6BC0',
    secondary: '#FFFFFF',
    others: [],
    category: 'websites',
    name: 'Discord',
  },
  {
    id: 20,
    link: ' assets/logos/minecraft.png',
    primary: '',
    secondary: '',
    others: ['#5A9A30', '#4F3624', '#946A49'],
    category: 'websites',
    name: 'Minecraft',
  },
  {
    id: 21,
    link: ' assets/logos/among-us.png',
    primary: '#F01717',
    secondary: '#000000',
    others: ['#75DBF4', '#FFFFFF',"#FCDD2A"],
    category: 'websites',
    name: 'Among Us',
  },
  {
    id: 22,
    link: ' assets/logos/reddit.png',
    primary: '#FF4500',
    secondary: '#FFFFFF',
    others: [],
    category: 'websites',
    name: 'Reddit',
  },
];
